name: Compile on multi OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Update submodules
      run: |
        git submodule init
        git submodule update --recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install libudev-dev
        sudo apt-get install libopenal-dev libvorbis-dev
        sudo apt-get install libsndfile1-dev
        sudo apt-get install libsfml-dev
        sudo apt-get install build-essential
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -DGLFW_USE_WAYLAND=ON
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest
